stages:
  - lint
  - test
  - build
  - upload

lint:
  tags:
    - docker
  stage: lint
  image: # docker with python 3.7 and pipenv installed
  script:
    - _CI/scripts/lint.py

test:
  tags:
    - docker
  stage: test
  image: # docker with python 3.7 and pipenv installed
  script:
    - _CI/scripts/test.py

build:
  tags:
    - docker
  stage: build
  image: # docker with python 3.7 and pipenv installed
  script:
    - _CI/scripts/build.py

upload:
  tags:
    - docker
  stage: upload
  image: # docker with python 3.7 and pipenv installed
  only:
    - tags
  script:
    - _CI/scripts/upload.py
